const CollectionActionsTypes = {
  // Fetch Collection At Intial Types
  FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
  FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
  FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE',

  // Pages Types
  FETCH_COLLECTION_NEXT_PAGE: 'FETCH_COLLECTION_NEXT_PAGE',
  COLLECTION_NEXT_PAGE: 'COLLECTION_NEXT_PAGE',
  FETCH_COLLECTION_NEXT_PAGE_SUCCESS: 'FETCH_COLLECTION_NEXT_PAGE_SUCCESS',

  // Input Search Fields Type
  SET_SEARCH_INPUT_FIELD: 'SET_SEARCH_INPUT_FIELD',

  // Search Collection Type
  SET_SEARCH_CATEGORY: 'SET_SEARCH_CATEGORY',
  
  // Collection BackupType 
  MAKE_COLLECTION_BACKUP: 'MAKE_COLLECTION_BACKUP'
};

export default CollectionActionsTypes;
