const universityActionTypes = {
  GET_USER_UNIVERSITY_START: "GET_USER_UNIVERSITY_START",
  GET_USER_UNIVERSITY_SUCCESS: "GET_USER_UNIVERSITY_SUCCESS",
  GET_USER_UNIVERSITY_FAILED: "GET_USER_UNIVERSITY_FAILED",
};

export default universityActionTypes;
