const universityActionTypes = {
  GET_USER_UNIVERSITY_START: 'GET_USER_UNIVERSITY_START',
  GET_USER_UNIVERSITY_SUCCESS: 'GET_USER_UNIVERSITY_SUCCESS',
  GET_USER_UNIVERSITY_FAILED: 'GET_USER_UNIVERSITY_FAILED',
  SET_UNIVERSITY_SORT_CATEGORY: 'SET_UNIVERSITY_SORT_CATEGORY',
  SET_PROPOSAL_ACCEPTANCE: 'SET_PROPOSAL_ACCEPTANCE',
  // University Settings
  TOGGLE_UNIVERSITY_SETTINGS: 'TOGGLE_UNIVERSITY_SETTINGS',
  REMOVE_UNIVERSITY_MEMBER: 'REMOVE_UNIVERSITY_MEMBER',
  
  ARCHIVE_PROPOSAL: 'ARCHIVE_PROPOSAL'
};

export default universityActionTypes;
